config/routes.rb
Bearsocial::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => 'sessions' }

  resources :posts do
    member do
      put 'star'
      put 'unstar'
    end
  end

  resources :users, :except => [:create, :new, :edit, :update] do
    member do
      put 'follow'
      put 'unfollow'
      put 'friend'
      put 'unfriend'
    end

    resource :profile
  end

  root :to => 'posts#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :enable_title, :jabber_id, :phone, :skype_id, :twitter_id, :locale, :timezone, :country, :city

  belongs_to :user

  validates_inclusion_of :locale, :in => I18n.available_locales.map { |s| s.to_s }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :build_profile

  def edit
  end

  def update

    respond_to do |format|

      if @user.update_attributes params[:user]
        flash[ :notice] = I18n.t('notices.profile_update_successful')
        format.html { redirect_to edit_user_profile_path(@user) }
        format.json { render :json => @user }
      else
        flash[:notice] = I18n.t('errors.profile_update_failed')
        format.html { render :action => 'edit' }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end


  end

  private
  def build_profile
    @user = User.find(params[:user_id])
    @user.build_profile unless @user.profile

    @user.profile.timezone ||= Time.zone.name
    @user.profile.country  ||= I18n.locale.to_s.upcase

    @user.profile.locale   ||= I18n.locale.to_s

  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
= twitter_bootstrap_form_for @user, :url => user_profile_path(@user)  do |f|
  = f.inputs do
    %legend= t('text.user_settings')
    = f.text_field :name
    = f.email_field :email, :input_html => { :disabled => !current_user.admin? }
    - if current_user.admin?
      = f.check_box :admin
    = f.text_field :avatar_url
    = f.password_field :password
    = f.password_field :password_confirmation
    = f.fields_for :profile do |p|
      %fieldset
        %legend= t('text.other_settings')
        = p.text_field :city
        /= p.text_field :country
        = p.select :locale, t('activerecord.attributes.profile.locale'), options_for_locale_select
        = p.country_select :country
        = p.time_zone_select :timezone
        = p.phone_field :phone
        = p.text_field :jabber_id, :class => 'xmpp'
        = p.text_field :skype_id, :add_on => :prepend do
          %span.add-on S
        = p.text_field :twitter_id, :add_on => :prepend do
          %span.add-on @
  = f.actions do
    = f.submit t('text.save')
    = button_tag t('text.cancel'), 'data-dismiss' => 'modal', :class => 'btn'