config/routes.rb
Bearsocial::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => 'sessions' }

  resources :posts do
    member do
      put 'star'
      put 'unstar'
    end
  end

  resources :users, :except => [:create, :new, :edit, :update] do
    member do
      put 'follow'
      put 'unfollow'
      put 'friend'
      put 'unfriend'
    end

    resource :profile
  end

  root :to => 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :encryptable, :confirmable,
         :lockable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :avatar_url, :profile_attributes
  # attr_accessible :title, :body

  has_many :followings

  has_many :friends, :through => :followings, :source => 'followed'

  has_many :followeds, :class_name => 'Following', :foreign_key => 'followed_id'
  has_many :followers, :through => :followeds, :source => :user

  has_many :posts

  has_one :profile
  accepts_nested_attributes_for :profile


  has_and_belongs_to_many :friends,
                          :class_name => "User",
                          :association_foreign_key => "friend_id",
                          :join_table => "friends_users"


  validates_presence_of :name

  validates_presence_of :avatar_url
  validates_format_of :avatar_url, :with => %r{^https?://(.*)$}

  before_validation :build_avatar_url
  #after_save :rebuild_friendships # Bidirectional friendship check

  def follows?(user)
    followings.where(:followed_id => user.id).any?
  end

  def followed_by?(user)
    user.followings.where(:followed_id => self.id).any?
  end

  def friend_of?(user)
    friend_ids.include?(user.id)
  end

  def password_required?
    !new_record? ? false : super
  end

  private

  # TODO move me to Resque task
  def rebuild_friendships
    friends.each do |f|
      unless f.friend_ids.include?(self.id)
        f.friends << self
        f.save
      end
    end
  end

  def build_avatar_url
    if avatar_url.blank? and not email.blank?
      gravatar_id = Digest::MD5::hexdigest(email).downcase
      self.avatar_url = "https://gravatar.com/avatar/#{gravatar_id}.png?r=pg"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  load_and_authorize_resource :except => :index

  def follow
    @following = current_user.followings.build(:followed_id => @user.id)

    respond_to do |format|
      if @following.save
        flash[:notice] = I18n.t('notices.you_now_following', :name => @user.name)
        format.json { render :json => {} }
      else
        flash[:error] = I18n.t('errors.you_cannot_follow', :name => @user.name)  # "You cannot follow #{@user.name}, because #{@following.errors.full_messages.to_sentence}"
        format.json { render :json => @following.errors, :status => :unprocessable_entity }
      end

      if request.xhr?
        format.html { render :text => "" }
      else
        format.html { redirect_to :back }
      end

    end
  end


  def unfollow
    @following = current_user.followings.where(:followed_id => @user.id).first
    @following.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render :json => {} }
    end
  end

  def friend
    current_user.friends << @user

    UserMailer.deliver_friend_email(current_user, @user)

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render :json => {} }
    end
  end

  def unfriend
    current_user.friends.delete(@user)

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render :json => {} }
    end
  end

  protected

  def collection
    @users ||= end_of_association_chain.page(params[:page])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/users/_sidebar.html.haml
.content-header
  .header-inner
    %h2 Friends
%ol.friends.users
  - current_user.friends.each do |friend|
    = render friend

app/views/users/_user.html.haml
%li.user{:id => "user-#{user.id}", :class => (current_user.follows?(user) ? "followed" : "nonfollowed") + (current_user.friend_of?(user) ? " friend" : " nonfriend")}
  .user-heading
    %a.account{:href => user_path(user), :class => 'profile-link'}
      = image_tag user.avatar_url, :class => 'avatar img-rounded', :size => '48x48'
      %strong.full-name= user.name
    %span &rlm;
    %span.username
      %b= user.email
  .user-slogan
    %br/
    = markdown(user.slogan || 'Lofasz')
  %nav.user-foot.clearfix
    %ul.friendbar.pull-right
      - if can? :update, user
        %li
          = link_to icon_tag('icon-pencil'), edit_user_path(user), :class => 'edit', :title => t('users.actions.edit')
      %li
        = link_to icon_tag('icon-eye-open'), follow_user_path(user), :class => 'follow', :title => t('users.actions.follow')
      %li
        = link_to icon_tag('icon-eye-close'), unfollow_user_path(user), :class => 'unfollow', :title => t('users.actions.unfollow')
      %li
        = link_to icon_tag('icon-heart'), friend_user_path(user), :class => 'befriend', :title => t('users.actions.friend')
      %li
        = link_to icon_tag('icon-tint'), unfriend_user_path(user), :class => 'unfriend', :title => t('users.actions.unfriend'), :confirm => t('questions.confirm_unfriend')
      - if can? :delete, user
        %li
          = link_to icon_tag('icon-trash'), user_path(user), :method => :delete, :confirm => t('questions.confirm_delete'), :title => t('users.actions.delete')

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
.content-header
  .header-inner
    %h2 Users
%ol.friends.users
  = render @users
  %li
    = paginate @users

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%ol.friends.users
  = render @user