config/routes.rb
Bearsocial::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => 'sessions' }

  resources :posts do
    member do
      put 'star'
      put 'unstar'
    end
  end

  resources :users, :except => [:create, :new, :edit, :update] do
    member do
      put 'follow'
      put 'unfollow'
      put 'friend'
      put 'unfriend'
    end

    resource :profile
  end

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  YOUTUBE_REGEX = %r{https?://(www\.)?(youtube.com/watch\?v=|youtu.be/)([a-zA-Z0-9]+)\S+}

  attr_accessor :video

  attr_accessible :author_id, :body, :deleted, :published, :title, :parent_post_id, :video


  belongs_to :parent_post, :class_name => 'Post'
  belongs_to :author, :class_name => 'User'

  has_many :stars
  has_many :replies, :class_name => 'Post', :foreign_key => 'parent_post_id'

  before_validation :build_title_and_slug
  before_save :replace_video_embed_code


  # TODO test race condition too!
  validates_presence_of :slug
  validates_uniqueness_of :slug
  validates_length_of :body, :maximum => 1000

  # validates_presence_of :body
  validates_length_of :body, :minimum => 1

  validates_format_of :video, :with => YOUTUBE_REGEX, :allow_blank => true

  def to_param
    slug
  end

  def starred_by?(user)
    stars.where(:user_id => user.id).any?
  end

  def self.friend_posts(user)
    uids = user.followings.collect(&:followed_id)
    uids << user.id
    where{ author_id >> uids }
  end

  private

  def replace_video_embed_code
    if self.body
      self.body = self.body.sub(
          YOUTUBE_REGEX,
          '<a href="http://youtu.be/\3" class="youtube-link"><img src="http://img.youtube.com/vi/\3/0.jpg" width="480" height="360" /></a>'
      )
    end
  end



  def build_title_and_slug
    build_title
    build_slug
  end

  # TODO move it to background task?
  # TODO or use slug gem?
  def build_slug
    if slug.blank? or title_changed?
      self.slug = self.title.blank? ? Time.now.strftime('%s') + id.to_s :  ActiveSupport::Inflector.transliterate(title).downcase.gsub(/[^\w]+/, '-')


      i = 0
      # Slug must be unique, so we try guess a good one
      loop do
        if Post.where(:slug => slug).count == 0
          break
        end
        i += 1
        if slug == 1
          slug = [slug, sprintf('%03d', i)].join('-')
        else
          orig_slug = slug.scan(/^(.+)-(\d+)$/).flatten.first
          slug = [orig_slug, sprintf('%03d', i)].join('-')
        end
      end
    end
  end

  # Builds a title if not present
  def build_title
    if title.blank?
      lines = body.to_s.strip.gsub(/\r\n/, "\n").split(/\n/)
      if lines.size > 0 and lines.first.match(/\A# (.*)\Z/)
        self.title = $1
        lines.shift
        self.body = lines.join("\n").strip
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  defaults :finder => :find_by_slug!
  load_and_authorize_resource :except => :index

  def star
    unless @post.starred_by?(current_user)
      star = @post.stars.create!(:user_id => current_user.id)

      respond_to do |format|
        format.json { render :json => star  }
        format.html { redirect_to :back }
      end
    end
  end

  def unstar
    if @post.starred_by?(current_user)
      @star = @post.stars.where(:user_id => current_user.id).first
      @star.destroy
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render :json => {} }
    end
  end

  def new
    if params[:parent]
      parent = Post.find(params[:parent])
      if parent
        @post = parent.replies.build
      end
    end
  end

  def create
    @post.author = current_user
    unless @post.video.blank?
      @post.body << "\n\n#{@post.video}"
    end
    create! do |success, failure|
      success.html { redirect_to posts_path }
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to posts_path }
    end
  end

  protected


  def collection
    @posts ||= Post.friend_posts(current_user).order('created_at DESC').page(params[:page])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
- if @post.parent_post
  - legend = "Reply"
- elsif not @post.new_record?
  - legend = "Edit post"
- else
  - legend = "New post"

- legend << sprintf('<div class="counter"><span class="label">%d</span></div>', (@post.body.try(:size) || 0))

= twitter_bootstrap_form_for @post, :html => { :class => 'post-form' } do |f|
  = f.inputs legend.html_safe do
    = f.text_area :body, false
    = f.hidden_field :parent_post_id
    = f.text_field :video, false, :class => 'youtube'
  = f.actions do
    = f.submit t('text.save') #, :class => 'btn btn-primary'
    = button_tag t('text.cancel'), :class => 'btn cancel', 'data-dismiss' => 'modal'

app/views/posts/_post.html.haml
- parent = defined?(@post) && @post.parent_post == post
%li.stream-item
  .post{:id => "post-#{post.id}", :class => (post.starred_by?(current_user) ? "starred" : "unstarred") + (parent ? " parent" : "")  }
    .post-heading
      %time.time{:datetime => post.created_at.strftime("%FT%T%:z")}
        = time_ago_in_words post.created_at
      %a.account{:href => user_path(post.author), :class => 'profile-link'}
        = image_tag post.author.avatar_url, :class => 'avatar img-rounded', :size => '48x48'
        %strong.full-name= post.author.name
      %span &rlm;
      %span.username
        %b= post.author.email
    .post-content
      %strong.post-title= post.title
      = markdown post.body
    %nav.post-foot.clearfix
      - if post.parent_post and not parent
        in reply to
        = link_to (post.parent_post.title || post.parent_post.slug), post_path(post.parent_post), :class => 'in-reply-to'

      %ul.sharebar.pull-right
        %li
          = link_to icon_tag('icon-chevron-right'), post_path(post), :title => t('posts.actions.show'), :class => 'show-post'
        - if can? :update, post
          %li
            =link_to icon_tag('icon-pencil'), edit_post_path(post), :title => t('posts.actions.edit'), :class => 'edit-post'
        %li
          = link_to icon_tag('icon-star'), unstar_post_path(post), :class => 'unstar', :title => t('posts.actions.unstar')
        %li
          = link_to icon_tag('icon-star-empty'), star_post_path(post), :class => 'star', :title => t('posts.actions.star')
        %li
          = link_to icon_tag('icon-comment'), new_post_path(:parent => post.id), :class => 'reply', :title => t('posts.actions.reply')
        - if can? :destroy, post
          %li
            = link_to icon_tag('icon-trash'), post, :method => :delete, :confirm => t('questions.confirm_delete'), :title => t('posts.actions.delete')

app/views/posts/edit.html.haml
- if @post.parent_post and not request.xhr?
  %ol.stream-items
    = render @post.parent_post
- else

= render 'form'

app/views/posts/index.html.haml
%main.page-container
  .content-header
    .header-inner
      %h2
        Listing posts
        = link_to icon_tag('icon-plus-sign'), new_post_path, :class => 'btn btn-small btn-success add-post'
  .posts-container
    %ol.stream-items
      = render @posts
      %li.stream-item
        = paginate @posts

app/views/posts/new.html.haml
- if @post.parent_post and not request.xhr?
  %ol.stream-items
    = render @post.parent_post
- else

= render 'form'

app/views/posts/show.html.haml
%main.page-container
  .posts-container
    %ol.stream-items
      - if @post.parent_post
        = render @post.parent_post
      = render @post
      = render @post.replies